name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: ThomasLandstra
          template: classic
          base: header
          config_timezone: Australia/Sydney
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_details: bytes-size, percentage
          plugin_languages_skipped: Model-Rocket-Hub, personal-dashboard, github-readme-stats, github-profile-trophy, dogehouse, a32nx, LARS-website
          plugin_lines: yes
          plugin_tweets: yes
          plugin_tweets_limit: 2
          plugin_tweets_user: .user.twitter
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          repositories_forks: yes
